# Generated by Django 2.2.7 on 2020-02-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part2',
            fields=[
                ('part2_id', models.AutoField(primary_key=True, serialize=False)),
                ('Nel', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Part2_2',
            fields=[
                ('part2_2_id', models.AutoField(primary_key=True, serialize=False)),
                ('Napp', models.FloatField(default=1)),
                ('Nvskrap', models.FloatField(default=1)),
            ],
        ),
    ]
