# Generated by Django 2.2.7 on 2020-02-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part2_2',
            name='Nvskrap',
            field=models.CharField(max_length=200),
        ),
    ]
