# Generated by Django 2.2.7 on 2020-02-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part2', '0002_part2_2_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part2_2',
            name='result',
            field=models.CharField(default='', max_length=4),
        ),
    ]
