# Generated by Django 2.2.7 on 2020-02-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part2', '0004_auto_20200220_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part2_2',
            name='Nvskrap',
            field=models.FloatField(default=1),
        ),
    ]
