# Generated by Django 2.2.7 on 2020-02-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mainmenu',
            fields=[
                ('mainmenu_id', models.AutoField(primary_key=True, serialize=False)),
                ('mainmenu_heading', models.CharField(max_length=250)),
                ('mainmenu_body', models.TextField()),
            ],
        ),
    ]
