# Generated by Django 2.2.7 on 2020-02-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part4',
            fields=[
                ('part4_id', models.AutoField(primary_key=True, serialize=False)),
                ('line_selected', models.FloatField(default=6)),
                ('canal_selected', models.FloatField(default=2)),
                ('number_val', models.FloatField(default=1)),
            ],
        ),
    ]
