# Generated by Django 2.2.7 on 2020-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part4',
            name='part4_body',
        ),
        migrations.RemoveField(
            model_name='part4',
            name='part4_heading',
        ),
        migrations.AddField(
            model_name='part4',
            name='part4_canal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='part4',
            name='part4_line',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='part4',
            name='part4_number_val',
            field=models.FloatField(default=0),
        ),
    ]
