# Generated by Django 2.2.7 on 2020-02-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part4_2',
            fields=[
                ('part4_2_id', models.AutoField(primary_key=True, serialize=False)),
                ('mestnost_selected', models.FloatField(default=1)),
                ('temp_val', models.FloatField(default=25)),
                ('snow_val', models.FloatField(default=0)),
                ('wind_val', models.FloatField(default=3)),
            ],
        ),
    ]
