# Generated by Django 2.2.7 on 2020-02-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part4', '0002_part4_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part4_3',
            fields=[
                ('part4_3_id', models.AutoField(primary_key=True, serialize=False)),
                ('stanciya_selected', models.FloatField(default=60)),
                ('marsh_val', models.FloatField(default=10)),
            ],
        ),
    ]
