# Generated by Django 2.2.7 on 2020-02-15 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part4', '0002_auto_20200215_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part4',
            old_name='part4_canal',
            new_name='canal_selected',
        ),
        migrations.RenameField(
            model_name='part4',
            old_name='part4_line',
            new_name='line_selected',
        ),
        migrations.RenameField(
            model_name='part4',
            old_name='part4_number_val',
            new_name='number_val',
        ),
    ]
