# Generated by Django 3.0.3 on 2020-02-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part1',
            fields=[
                ('part1_id', models.AutoField(primary_key=True, serialize=False)),
                ('Elements', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Part1_2',
            fields=[
                ('part1_2_id', models.AutoField(primary_key=True, serialize=False)),
                ('Sc', models.FloatField(default=1)),
                ('Smax', models.FloatField(default=1)),
                ('result', models.CharField(default='', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Part1_3',
            fields=[
                ('part1_3_id', models.AutoField(primary_key=True, serialize=False)),
                ('Nvapp', models.FloatField(default=1)),
                ('Nap', models.FloatField(default=1)),
                ('Peffpvo', models.FloatField(default=1)),
                ('Peffreb', models.FloatField(default=1)),
                ('result', models.CharField(default='', max_length=4)),
            ],
        ),
    ]
