# Generated by Django 3.0.3 on 2020-02-29 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part1',
            old_name='Elements',
            new_name='NumChastey',
        ),
    ]
