# Generated by Django 3.0.3 on 2020-02-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0002_auto_20200229_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page1BezRazdel',
            fields=[
                ('Page1BezRazdel_id', models.AutoField(primary_key=True, serialize=False)),
                ('Kir', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Part1_2',
        ),
    ]
