# Generated by Django 3.0.3 on 2020-02-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0003_auto_20200229_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page1CoupleWays1',
            fields=[
                ('Page1CoupleWays1_id', models.AutoField(primary_key=True, serialize=False)),
                ('Kir', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Page1CoupleWays2',
            fields=[
                ('Page1CoupleWays2_id', models.AutoField(primary_key=True, serialize=False)),
                ('Kir', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Page1OneWay',
            fields=[
                ('Page1OneWay_id', models.AutoField(primary_key=True, serialize=False)),
                ('Kir', models.FloatField(default=0)),
            ],
        ),
    ]
