# Generated by Django 3.0.3 on 2020-02-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0004_page1coupleways1_page1coupleways2_page1oneway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page1OneWay2',
            fields=[
                ('Page1OneWay2_id', models.AutoField(primary_key=True, serialize=False)),
                ('Kir', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Page1OneWay',
            new_name='Page1OneWay1',
        ),
        migrations.RenameField(
            model_name='page1oneway1',
            old_name='Page1OneWay_id',
            new_name='Page1OneWay1_id',
        ),
    ]
