# Generated by Django 3.0.3 on 2020-03-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0005_auto_20200229_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page1Recogn',
            fields=[
                ('Page1Recogn_id', models.AutoField(primary_key=True, serialize=False)),
                ('chasov', models.FloatField(default=0)),
                ('mins', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Page1TimeMarsh',
            fields=[
                ('Page1TimeMarsh_id', models.AutoField(primary_key=True, serialize=False)),
                ('Tr', models.FloatField(default=0)),
            ],
        ),
    ]
