# Generated by Django 3.0.3 on 2020-03-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0006_page1recogn_page1timemarsh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page1BezSostav',
            fields=[
                ('Page1BezSostav_id', models.AutoField(primary_key=True, serialize=False)),
                ('SumTimeDay', models.FloatField(default=0)),
                ('SumTimeNight', models.FloatField(default=0)),
            ],
        ),
    ]
