# Generated by Django 3.0.3 on 2020-03-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0007_page1bezsostav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page1timemarsh',
            old_name='Tr',
            new_name='Tm',
        ),
    ]
