# Generated by Django 3.0.3 on 2020-03-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0008_auto_20200310_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='page1timemarsh',
            name='Tmbez',
            field=models.FloatField(default=0),
        ),
    ]
