# Generated by Django 3.0.3 on 2020-03-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0009_page1timemarsh_tmbez'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page1TimeRazv',
            fields=[
                ('Page1TimeRazv_id', models.AutoField(primary_key=True, serialize=False)),
                ('Trazv', models.FloatField(default=0)),
                ('Tsvert', models.FloatField(default=0)),
            ],
        ),
    ]
