# Generated by Django 3.0.3 on 2020-03-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0010_page1timerazv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page1RazOneSostav1',
            fields=[
                ('Page1BezSostav_id', models.AutoField(primary_key=True, serialize=False)),
                ('SumTimeDay', models.FloatField(default=0)),
                ('SumTimeNight', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Page1Recogn1',
            fields=[
                ('Page1Recogn_id', models.AutoField(primary_key=True, serialize=False)),
                ('chasov', models.FloatField(default=0)),
                ('mins', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Page1TimeMarsh1',
            fields=[
                ('Page1TimeMarsh_id', models.AutoField(primary_key=True, serialize=False)),
                ('Tmbez', models.FloatField(default=0)),
                ('Tm', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Page1TimeRazv1',
            fields=[
                ('Page1TimeRazv_id', models.AutoField(primary_key=True, serialize=False)),
                ('Trazv', models.FloatField(default=0)),
                ('Tsvert', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Page1OneWay2',
        ),
    ]
