# Generated by Django 3.0.3 on 2020-03-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0011_auto_20200320_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page1RazCoupleSostav1',
            fields=[
                ('Page1BezSostav_id', models.AutoField(primary_key=True, serialize=False)),
                ('SumTimeDay', models.FloatField(default=0)),
                ('SumTimeNight', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Page1Recogn2',
            fields=[
                ('Page1Recogn_id', models.AutoField(primary_key=True, serialize=False)),
                ('chasov', models.FloatField(default=0)),
                ('mins', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Page1TimeMarsh2',
            fields=[
                ('Page1TimeMarsh_id', models.AutoField(primary_key=True, serialize=False)),
                ('Tmbez', models.FloatField(default=0)),
                ('Tm', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Page1TimeRazv2',
            fields=[
                ('Page1TimeRazv_id', models.AutoField(primary_key=True, serialize=False)),
                ('Trazv', models.FloatField(default=0)),
                ('Tsvert', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Page1CoupleWays2',
        ),
    ]
