# Generated by Django 2.2.7 on 2020-02-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part3', '0002_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Part3',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.RenameField(
            model_name='part3',
            old_name='article_body',
            new_name='part3_body',
        ),
        migrations.RenameField(
            model_name='part3',
            old_name='article_heading',
            new_name='part3_heading',
        ),
        migrations.RenameField(
            model_name='part3',
            old_name='article_id',
            new_name='part3_id',
        ),
    ]
