# Generated by Django 2.2.7 on 2020-02-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part3', '0003_auto_20200214_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part3',
            name='part3_body',
        ),
        migrations.RemoveField(
            model_name='part3',
            name='part3_heading',
        ),
        migrations.AddField(
            model_name='part3',
            name='Nel_3',
            field=models.FloatField(default=1),
        ),
    ]
