# Generated by Django 2.2.7 on 2020-02-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part3', '0004_auto_20200227_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part3',
            old_name='Nel_3',
            new_name='Elements',
        ),
    ]
