# Generated by Django 2.2.7 on 2020-02-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part3', '0005_auto_20200227_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part3_2',
            fields=[
                ('part3_2_id', models.AutoField(primary_key=True, serialize=False)),
                ('Sc', models.FloatField(default=1)),
                ('Smax', models.FloatField(default=1)),
                ('result', models.CharField(default='', max_length=4)),
            ],
        ),
    ]
