# Generated by Django 2.2.7 on 2020-02-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part3', '0006_part3_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part3_3',
            fields=[
                ('part3_3_id', models.AutoField(primary_key=True, serialize=False)),
                ('Nvapp', models.FloatField(default=1)),
                ('Nap', models.FloatField(default=1)),
                ('Peffpvo', models.FloatField(default=1)),
                ('Peffreb', models.FloatField(default=1)),
                ('result', models.CharField(default='', max_length=4)),
            ],
        ),
    ]
